// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoenZ0E_LxLDmhD5nRV0iCFXwJkj64m4I',
    appId: '1:105470290830:web:5521c22f258b58dcd9d2df',
    messagingSenderId: '105470290830',
    projectId: 'enrregulations',
    authDomain: 'enrregulations.firebaseapp.com',
    storageBucket: 'enrregulations.appspot.com',
    measurementId: 'G-9TB076SD5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4zBDMdFOoL76W5dEyU3BF5yNVdvonWQ',
    appId: '1:105470290830:android:34449189a0df7eb1d9d2df',
    messagingSenderId: '105470290830',
    projectId: 'enrregulations',
    storageBucket: 'enrregulations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe98y6wl0ihOaCLVqWsXpe03R0sCCsUdA',
    appId: '1:105470290830:ios:ec9ca8e310ecdc49d9d2df',
    messagingSenderId: '105470290830',
    projectId: 'enrregulations',
    storageBucket: 'enrregulations.appspot.com',
    iosClientId: '105470290830-o6mo4bq8r25sk4kbfakdu1ard81jakhu.apps.googleusercontent.com',
    iosBundleId: 'com.aliDekheel.enrRegulations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe98y6wl0ihOaCLVqWsXpe03R0sCCsUdA',
    appId: '1:105470290830:ios:ec9ca8e310ecdc49d9d2df',
    messagingSenderId: '105470290830',
    projectId: 'enrregulations',
    storageBucket: 'enrregulations.appspot.com',
    iosClientId: '105470290830-o6mo4bq8r25sk4kbfakdu1ard81jakhu.apps.googleusercontent.com',
    iosBundleId: 'com.aliDekheel.enrRegulations',
  );
}
